apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-provider.fullname" . }}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation

type: Opaque
stringData:
  flyway-user: "postgres"
  flyway-password: "password"
  db-user: "postgres"
  db-password: "password"